name: covid_19_brasil
description: Mapa para análise de casos do Coronavírus no Brasil

version: 1.5.2

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  charts_flutter: ^0.9.0
  date_format: ^1.0.8
  firebase_analytics: ^5.0.11
  firebase_messaging: ^6.0.13
  flutter_typeahead: ^1.8.0
  flutter_cache_manager: ^1.1.1
  google_maps_flutter: ^0.5.26
  loading_overlay: ^0.2.1
  package_info: ^0.4.0+16
  sliding_up_panel: ^1.0.2
  splashscreen: ^1.2.0
  vibration: ^1.2.4
  webview_flutter: ^0.3.19+9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "icon/icon2.png" 
  android: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/pin-city.png
    - assets/images/pin-state.png
    - assets/images/pin-country.png
    - assets/images/img_menu.png
    - assets/map-style.txt
