name: covid_19_brasil
description: Mapa para análise de casos do Coronavírus no Brasil

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Icon package for iOS
  cupertino_icons: ^0.1.2

  # Google maps
  google_maps_flutter: ^0.5.21+3

  # Map markers clustering
  fluster: ^1.1.2

  # Cache manager
  flutter_cache_manager: ^1.1.1

  path_provider: ^1.6.5

  flutter_downloader: ^1.4.1

  webview_flutter: ^0.3.19+9

  flutter_launcher_icons: ^0.7.4

  fl_animated_linechart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "icon/icon2.png" 
  android: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/pin-city.png
